name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW 
