name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install npm
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Angular project
        run: ng build --prod
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ajiqbrainx/front:7
      - name: Create kubeconfig
        run: |
         mkdir ${HOME}/.kube
         echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
         cat ${HOME}/.kube/config
      - name: Get namespace
        run: kubectl get namespace
      - name: Get Pods
        run: kubectl get pods -n flexcub-testing
      
